//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profiler
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorsProfile
    {
        public int DoctorID { get; set; }
        public Nullable<int> HPCSANo { get; set; }
        public Nullable<int> IDNo { get; set; }
        public string Title { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Discipline { get; set; }
        public string Province { get; set; }
        public string Region { get; set; }
    }
}
